apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-app
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: 'https://github.com/ArkadiiMinenko/for-final-pr-app.git'
    targetRevision: HEAD
    path: app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
