spec:
  source:
    repoURL: https://github.com/ArkadiiMinenko/for-final-pr-app.git
    targetRevision: main
    path: app
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
