server:
  extraArgs:
    - --insecure
  ingress:
    enabled: true
    ingressClassName: nginx
    hostname: ${hostname}
    annotations:
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
      external-dns.alpha.kubernetes.io/hostname: ${hostname}
    paths:
      - /
    pathType: Prefix
