server:
  extraArgs:
    - --insecure
  ingress:
    enabled: true
    ingressClassName: nginx
    hostname: ${hostname}
    annotations:
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
    paths:
      - /
    pathType: Prefix

configs:
  secret:
    createSecret: true
