# .github/workflows/test-docker-login.yml
name: Test Docker Hub Login

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  login-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Test Docker login
        run: |
          echo "Спроба входу в Docker Hub…"
          docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" -p "${{ secrets.DOCKERHUB_TOKEN }}"
        shell: bash
