# .github/workflows/debug-docker-login.yml
name: Debug Docker Login

on:
  workflow_dispatch:  # дозволяє запускати вручну з UI Actions

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Debug secret presence and length
        run: |
          echo "DOCKER_USERNAME set? $( [ -z \"$DOCKER_USERNAME\" ] && echo no || echo yes )"
          echo "DOCKER_USERNAME length: $(echo -n \"$DOCKER_USERNAME\" | wc -c)"
          echo "DOCKER_PASSWORD set? $( [ -z \"$DOCKER_PASSWORD\" ] && echo no || echo yes )"
          echo "DOCKER_PASSWORD length: $(echo -n \"$DOCKER_PASSWORD\" | wc -c)"

      - name: Manual Docker login (debug)
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
