name: Build & Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set SHORT_TAG from commit SHA
        run: echo "SHORT_TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" \
            | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
        shell: bash

      - name: Build & Push Image
        run: |
          USERNAME="${{ secrets.DOCKERHUB_USERNAME }}"
          USERNAME="${USERNAME//$'\n'/}"
          USERNAME="${USERNAME//$'\r'/}"

          IMAGE="$USERNAME/devops1-app:$SHORT_TAG"
          echo "Building $IMAGE from ./app..."
          docker build -t "$IMAGE" -f app/Dockerfile app
          echo "Pushing $IMAGE"
          docker push "$IMAGE"
        shell: bash

      - name: Update deployment.yaml with new tag
        run: |
          USERNAME="${{ secrets.DOCKERHUB_USERNAME }}"
          USERNAME="${USERNAME//$'\n'/}"
          USERNAME="${USERNAME//$'\r'/}"

          IMAGE="$USERNAME/devops1-app:$SHORT_TAG"
          echo "Replacing image with: $IMAGE"
          sed -i "s#image: .*/devops1-app:.*#image: $IMAGE#" app/deployment.yaml
        shell: bash
