name: Build & Push Docker Image

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set TAG from commit SHA
        run: echo "TAG=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV

      - name: Docker login
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build & Push Docker image
        env:
          DOCKER_BUILDKIT: 0
        run: |
          docker build -t $DOCKERHUB_USERNAME/devops1-app:$TAG -f app/Dockerfile app/
          docker push $DOCKERHUB_USERNAME/devops1-app:$TAG


      - name: Update deployment.yaml with new tag
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          TAG: ${{ env.TAG }}
        run: |
          sed -i "s|image: .*/devops1-app:.*|image: $DOCKERHUB_USERNAME/devops1-app:$TAG|" app/deployment.yaml

      - name: Commit & Push updated YAML
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add app/deployment.yaml
          git commit -m "Update image tag to ${TAG}"
          git push
