name: Build & Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set SHORT_TAG from commit SHA
        run: echo "SHORT_TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Docker login
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

      - name: Build & Push Docker image
        run: |
          echo "Building image: $DOCKERHUB_USERNAME/devops1-app:$SHORT_TAG"
          docker build -t $DOCKERHUB_USERNAME/devops1-app:$SHORT_TAG -f app/Dockerfile app/
          docker push $DOCKERHUB_USERNAME/devops1-app:$SHORT_TAG

      - name: Update deployment.yaml with new tag
        run: |
          sed -i "s|image: .*/devops1-app:.*|image: $DOCKERHUB_USERNAME/devops1-app:$SHORT_TAG|" app/deployment.yaml

      - name: Commit & Push updated YAML
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add app/deployment.yaml
          git commit -m "Update image tag to $SHORT_TAG"
          git push
