name: Debug Docker Login

# Тригер — ручний запуск з UI
on:
  workflow_dispatch:

jobs:
  debug-login:
    runs-on: ubuntu-latest
    env:
      # Передаємо секрети в змінні середовища
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Show secret presence and length
        run: |
          echo "🛡️ DOCKER_USERNAME set? $( [ -z \"$DOCKER_USERNAME\" ] && echo no || echo yes )"
          echo "🔢 DOCKER_USERNAME length: $(echo -n \"$DOCKER_USERNAME\" | wc -c)"
          echo "🛡️ DOCKER_PASSWORD set? $( [ -z \"$DOCKER_PASSWORD\" ] && echo no || echo yes )"
          echo "🔢 DOCKER_PASSWORD length: $(echo -n \"$DOCKER_PASSWORD\" | wc -c)"

      - name: Manual Docker login
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
