name: Build & Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set SHORT_TAG from commit SHA
        run: echo "SHORT_TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Docker login
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        run: echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

      - name: Debug check
        run: |
          echo "CURRENT WORKFLOW VERSION: docker-publish.yml updated"

      - name: Build & Push Docker image
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        run: |
          echo "Building image: $DOCKERHUB_USERNAME/devops1-app:$SHORT_TAG"
          docker build -t $DOCKERHUB_USERNAME/devops1-app:$SHORT_TAG -f app/Dockerfile app/
          docker push $DOCKERHUB_USERNAME/devops1-app:$SHORT_TAG

      - name: Update deployment.yaml with new tag
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        run: |
          sed -i "s|image: .*/devops1-app:.*|image: $DOCKERHUB_USERNAME/devops1-_
